name: Mamba build minimal test


on:
  pull_request:
  
jobs:
  mamba_build:
    name: Testing mamba build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false 
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up MSVC (Windows only)
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Delete Incorrect Link from Path
        if: matrix.os == 'windows-latest'
        run: rm /usr/bin/link.exe
        
      - name: Install micromamba
        uses: mamba-org/setup-micromamba@v2
        env:
          ACTIONS_STEP_DEBUG: true
        with:
          init-shell: >-
            bash
          create-args: >-
            python=3.11
            conda
          environment-name: molli

      - name: Install conda build and upload dependencies
        run: |
          conda install boa;
          conda install conda-verify;

      - name: Build package
        env:
          ACTIONS_STEP_DEBUG: true
        run: |
          mkdir conda-dist;
          conda mambabuild conda-recipe --output-folder conda-dist --no-anaconda-upload --python 3.13;
